[package]
name = "yolo_v11"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "yolo_v11"
path = "src/main.rs"

[features]

[dependencies]
luminal = { path = "../.." }
tikv-jemallocator = { version = "0.7", features = ["unprefixed_malloc_on_supported_platforms"] }
luminal_cuda_lite = { path = "../../crates/luminal_cuda_lite" }
luminal_tracing = { path = "../../crates/luminal_tracing" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

safetensors = "0.7.0"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
ureq = "2"
